[book]
authors = ["Emil Lindfors"]
language = "en"
multilingual = false
src = "src"
title = "HVL AI Dev Docs"

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.xgettext]
optional = true
pot-file = "messages.pot"
granularity = 0

[output.html]
smart-punctuation = true
additional-css = [
  "theme/css/language-picker.css",
]
site-url = "/docs/"
git-repository-url = "https://github.com/HVL-ML/docs"
edit-url-template = "https://github.com/HVL-ML/docs/edit/main/{path}"

[output.html.fold]
enable = true
level = 0
