name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  
  steps:
    - name: Install mdbook
      uses: cargo-bins/cargo-binstall@main
      with:
        crate: mdbook
        version: 0.4.37

    #- name: Install mdbook-svgbob
    #  run: cargo install mdbook-svgbob --locked --version 0.2.1
    #  shell: bash

    #- name: Install mdbook-pandoc and related dependencies
    #  run: |
    #    cargo install mdbook-pandoc --locked --version 0.7.0
    #    sudo apt-get update
    #    sudo apt-get install -y texlive texlive-luatex texlive-lang-cjk librsvg2-bin fonts-noto
    #    curl -LsSf https://github.com/jgm/pandoc/releases/download/3.2.1/pandoc-3.2.1-linux-amd64.tar.gz | tar zxf -
    #    echo "$PWD/pandoc-3.2.1/bin" >> $GITHUB_PATH
    #  shell: bash

    - name: Install mdbook-i18n-helpers
      run: cargo install mdbook-i18n-helpers --locked --version 0.3.3
      shell: bash

    - name: Install i18n-report
      run: cargo install i18n-report --locked --version 0.2.0
      shell: bash
